#define UCSRB UCSR1B
#define UDRIE UDRIE1
#define UDR UDR1
#define UBRRH UBRR1H
#define UBRRL UBRR1L
#define RXEN RXEN1
#define TXEN TXEN1
#define RXCIE RXCIE1
#define UCSRC UCSR1C
#define URSEL 7
#define UCSZ0 UCSZ10
#define USART_RXC_vect USART1_RX_vect
#define USART_UDRE_vect USART1_UDRE_vect
